name: Run Scraping Pipeline

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare Output Directory
        run: |
          mkdir -p "${{ github.workspace }}/output"
          chmod 777 "${{ github.workspace }}/output"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t my-project:latest .

      - name: Run Pipeline in Container
        run: docker run --rm -v "${{ github.workspace }}/output:/app/output" my-project:latest

      - name: Package Artifacts
        run: python src/utils/package_artifacts.py --output-path output --archive-name release_artifacts_${{ github.run_number }}.zip

      # Create a release and upload the artifact using a maintained action
      - name: Create GitHub Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          tag: "release-${{ github.run_number }}"
          name: "Release ${{ github.run_number }}"
          artifacts: release_artifacts_${{ github.run_number }}.zip
